server-name: "" #used for clans
enderpearl-cooldown: 16

settings:
  locations:
    spawn: ""
  countdown:
    event: 5
    match: 5
    tournament: 5

mongo:
  uri-mode: false
  normal:
    host: 127.0.0.1
    port: 27017
    auth:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Practice
    connection-string: mongodb://127.0.0.1:27017/Practice